name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: Linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install python2
      run: |
        sudo apt-get update
        sudo apt-get install python2
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,bioconda,default
        python-version: ${{ matrix.python-version }}
    - name: Install repo
      run: python -m pip install --no-deps .
    - name: Install snakemake
      run: mamba install snakemake numpy
    - name: Test workflow with amibo cli (local test data)
      run: amibo test --show-failed-logs -j 2 --conda-cleanup-pkgs cache --use-conda
    - name: cache-conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 2
      with:
        path: .test/.snakemake/conda
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('workflow/envs/*.yaml') }}
      id: cache

    - name: Install workflow environments
      uses: snakemake/snakemake-github-action@v1.24.0
      if: steps.cache-conda.outputs.cache-hit != 'true'
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --conda-create-envs-only"

    - name: Build krakenuniq database
      working-directory: .test
      run: |
        env=$(grep krakenuniq .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        krakenuniq-build --db resources/KrakenUniq_DB --kmer-len 21 --minimizer-len 11 --jellyfish-bin $(pwd)/$env/bin/jellyfish
        conda deactivate

    - name: Build krona taxonomy
      working-directory: .test
      run: |
        env=$(grep krona .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        cd $env/opt/krona
        sudo ./updateTaxonomy.sh taxonomy
        conda deactivate

    - name: Adjust malt maximum memory usage
      working-directory: .test
      run: |
        env=$(grep hops .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        version=$(conda list malt --json | grep version | sed -e "s/\"//g" | awk '{print $2}')
        cd $env/opt/malt-$version
        sudo sed -i -e "s/-Xmx64G/-Xmx3G/" malt-build.vmoptions
        sudo sed -i -e "s/-Xmx64G/-Xmx3G/" malt-run.vmoptions
        conda deactivate

    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--show-failed-logs -j 2 --use-conda -p"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
