name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/amibo
        snakefile: src/amibo/workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: Linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: cache-conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 2
      with:
        path: src/amibo/.test/.snakemake/conda
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('workflow/envs/*.yaml') }}
      id: cache

    - name: Install amibo package
      run: |
        python -m pip install -e .

    - name: Install workflow environments
      uses: snakemake/snakemake-github-action@v1
      if: steps.cache-conda.outputs.cache-hit != 'true'
      with:
        directory: src/amibo/.test
        snakefile: src/amibo/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --conda-create-envs-only"

    - name: Build krakenuniq database
      working-directory: src/amibo/.test
      run: |
        env=$(grep krakenuniq .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        krakenuniq-build --db resources/KrakenUniq_DB --kmer-len 21 --minimizer-len 11
        conda deactivate

    - name: Build krona taxonomy
      working-directory: src/amibo/.test
      run: |
        env=$(grep krona .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        cd $env/opt/krona
        sudo ./updateTaxonomy.sh taxonomy
        conda deactivate

    - name: Adjust malt maximum memory usage
      working-directory: src/amibo/.test
      run: |
        env=$(grep hops .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $env
        version=$(conda list malt --json | grep version | sed -e "s/\"//g" | awk '{print $2}')
        cd $env/opt/malt-$version
        sudo sed -i -e "s/-Xmx64G/-Xmx3G/" malt-build.vmoptions
        sudo sed -i -e "s/-Xmx64G/-Xmx3G/" malt-run.vmoptions
        conda deactivate

    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/amibo/.test
        snakefile: src/amibo/workflow/Snakefile
        args: "--show-failed-logs -j 2 --use-conda -p"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/amibo/.test
        snakefile: src/amibo/workflow/Snakefile
        args: "--report report.zip"
